name: dagashi_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # For Networking
  dio: ^3.0.10
  ua_client_hints: ^1.0.3

  # Convert between Enum and String
  enum_to_string: ^1.0.14

  # For Model
  json_serializable: ^3.5.1
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11

  # For Model
  freezed: ^0.12.5

flutter:
  uses-material-design: true
